print(" *                *            * ")
print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")
//my name is rohan arya
print("RRRR ")
print("R   R")
print("R   R")
print("RRRR ")
print("R R  ")
print("R  R ")
print("R   R")
//NOW MY SECOND INITIAL
print("  A  ")
print(" A A ")
print("A   A")
print("AAAAA")
print("A   A")
print("A   A")
print("A   A")